### ISSUE TITLE
HPE Components Sticker Sheet 1.0 - Adobe XD

### ISSUE THREAD

**Issue by bryanjacquot** [grommet/grommet-design#15]
Create PSD version of the sticker sheets that align with existing HPE and Grommet sticker sheets for designers who prefer to use PhotoShop.

**Comment by dgennetten** [comment]
I'd be happy to take this task. I'm assuming it should draft #38?

**Comment by tracybarmore** [comment]
Changed card to be Adobe XD General Sticker Sheet.

**Comment by JetLim** [comment]
'Pull Request' sent to L0ZZI and Tracy for review. 
- Add hpe-components-1.0 - Adobe XD #83

**Comment by L0ZZI** [comment]
We're going to do this a little different in v2. Standby...
