### ISSUE TITLE
Add guidance on time and date formats

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/grommet-design#20]
I get questions here and there about the recommendations on how to display time and date content in a variety of contexts. It would be good if grommet.io had a section on time and date format guidance.

**Comment by bryanjacquot** [comment]
There's a bit of info here: http://www.grommet.io/docs/hpe/design/date-and-time.  What more should be added?

**Comment by tracybarmore** [comment]
Closing issue. Documentation present.
