### ISSUE TITLE
Edit 16x16 status icon color - HPE/Grommet sticker sheets

### ISSUE THREAD

**Issue by tracybarmore** [grommet/grommet-design#21]
Need to change 16x16 status icon colors to #333 to meet accessibility contrast standards.

**Comment by bryanjacquot** [comment]
One option is to use #333 for small icons, but use shape of larger icons for accessible coding.

**Comment by L0ZZI** [comment]
Close, no change. The color density of the status icons is strong enough at small sizes as the color is solid. The WCAG AA spec specifies that text and images of text satisfy need to be 19px, bold, and 3:1 contrast. it could be interpreted that that the icons don't need to satisfy this with an accompanying alt text.
