### ISSUE TITLE
High priority updates to Sticker Sheets

### ISSUE THREAD

**Issue by bryanjacquot** [grommet/grommet-design#28]
The 0.9.4 sticker sheets have a few key differences from the latest design pattern and implementation.   Specifically:
- [x] Checkbox style
- [x] Radio buttons are close, but the selected circle is slightly smaller than implementation
- [x] Form design (where errors are displayed)
- [x] Tab styling (style of selected item's underline and underline on hover)

**Comment by L0ZZI** [comment]
Note on the dev implementation of Tabs is that the weight of the links should all be HPE Metric Semibold. I'll make the change on that side.

**Comment by L0ZZI** [comment]
Closed by lozzi with commit  dbd5fe9f32117cbf43b8ed61507e38fbc3d7eaf3

**Comment by L0ZZI** [comment]
Added changes to Illustrator and PDF files in commit 4811331
