### ISSUE TITLE
xsmall core icons

### ISSUE THREAD

**Issue by tracybarmore** [grommet/grommet-design#33]
The need for xsmall core icons issue is related to and can impact sorting on table headers.

**Comment by L0ZZI** [comment]
Adding to sticker sheet.

**Comment by L0ZZI** [comment]
Align socialShare, Status and Icon Small approaches for the icon loader. Unify  the colorIndex across all icon types. Icon Small property should integrate SVG icons with multiple art boards into separate classes.
