### ISSUE TITLE
1.	Zoom in/out functionality for grommet charts  

### ISSUE THREAD

**Issue by agrawalPratik** [grommet/grommet-design#34]
@ericsoderberghp @L0ZZI @bryanjacquot 
Requirement are as follows:

1.  User should be able to zoom in/out in all grommet chart components
2.  Zoom in/out functionality should can be done by user via mouse wheel, partial selection done on the graph, range selector controlling chart
3. User should be able to reset the graph any time 

Below is the link for grommet chart
https://grommet.github.io/docs/chart/examples/#15

**Comment by L0ZZI** [comment]
This is not in scope for the near future. After reviewing with @ericsoderberghp we would recommend using alternative ways of delving into your data (secondary control that allows user to set timeframe, interval, etc). The level of interaction required to do the level of inspection your asking would require a framework unto itself to support navigation of data.

The team tries to make components that provide the right amount of functionality for most experiences. We like to think that the visualization tools we provide do one part of the lifting for the UI, but the other half is the shaping your data to fit a mobile first experience.
