### ISSUE TITLE
Hint customers for content below the fold 

### ISSUE THREAD

**Issue by agrawalPratik** [grommet/grommet-design#35]
There is a requirement for content heavy pages wherein user should have cues that there is more content below the fold.

**Comment by agrawalPratik** [comment]
can we pattern similar to invision app wherein they use Left/Right Arrows for switching screenshot, we can have similar pattern for scroll up and down.

**Comment by L0ZZI** [comment]
I would recommend having key actions anchored in your header/above the fold and then replicated at the end of the form if they are that crucial. 

I would say the biggest change you could make to your form/content is by asking the essential information of what we need from users and/or presenting the pertinent information and ask all other questions after or secondary data below the fold.

You can use the anchor as this cue today point to other headings on the page. I would avoid sticky footers or floating buttons as there would be more to manage.
