### ISSUE TITLE
Need clear filter functionality

### ISSUE THREAD

**Issue by agrawalPratik** [grommet/grommet-design#36]
@ericsoderberghp @L0ZZI @bryanjacquot 

Need clear filter functionality in filter component
http://index.grommet.io/docs/grommet-index/filters

**Comment by L0ZZI** [comment]
You can do this today. There us nothing preventing you from doing this in grommet. I would assume you just add a button that states, "Reset to Default Values" or something to that nature at the bottom or wherever you're anchoring your controls.

**Comment by agrawalPratik** [comment]
do you mean that we should add that anchor in the filter dialogs/boxes?
