### ISSUE TITLE
Functionality to rearrange Dashboard tiles as per user preference

### ISSUE THREAD

**Issue by agrawalPratik** [grommet/grommet-design#37]
@ericsoderberghp @L0ZZI @bryanjacquot 
A solution for rearranging the cards on dashboard as per the user preference i.e. Drag and drop the cards as per user preference.

Also if user close/hide tile on dashboard then automatically all the other tile should automatically re-adjust themselves

**Comment by L0ZZI** [comment]
We're investigating. We're doing a little design proposal on our end to suss out the interaction. Not release timeline yet.

**Comment by L0ZZI** [comment]
Any fit criteria you have on your end to add to the feature?

**Comment by agrawalPratik** [comment]
Do you mean criteria from users interaction perspective?
