### ISSUE TITLE
Show count of items left/viewed when lazy loading / Infinite scroll

### ISSUE THREAD

**Issue by agrawalPratik** [grommet/grommet-design#39]
@ericsoderberghp @L0ZZI @bryanjacquot 
Requirement is there are few pages wherein we have lots of items available in a form of list/tiles, in this case lazy loading is used, but user has no clue that how many items are still left on the page so for that we need some cue to show the total no. of items are still left to be viewed and no. of items loaded/viewed.

**Comment by L0ZZI** [comment]
Depending on how yours getting your counts on your backend, there's nothing stopping you from working the count in the heading a sub-head, and/or mixing the total into the filter.

 I would assume the total count is less important than filtered data set count? Let me know if you need a mock of how it would be shown.

**Comment by agrawalPratik** [comment]
Yes it would be great if you can provide one screen for that, so that its easy to understand.
