### ISSUE TITLE
Cannot Read Property 'componentWillLeave' When Using Accordion Control

### ISSUE THREAD

**Issue by jessegoraya** [grommet/grommet-design#81]
Hello,
I'm using the accordion control and it properly opens, however when trying to close the accordion it does not close and get an error.  The error in the console states "Cannot read property 'componentWillLeave' of undefined at ReactTransitionGroup._thisPeformLeave.

Any thoughts on how to fix?

**Comment by tracybarmore** [comment]
Hey @jessegoraya, thanks for finding this issue. But, I believe you may have opened this card under the incorrect repo. This repo (grommet/grommet-design) is for grommet designers. Your issue sounds like it should be opened in grommet/grommet so our grommet developers can look in to it. Let me know if you have any questions. Thanks!
