### ISSUE TITLE
Request: Sketch Libraries

### ISSUE THREAD

**Issue by Primajin** [grommet/grommet-design#93]
[Sketch 47](https://sketchapp.com/beta/) will introduce [libraries](https://sketchapp.com/learn/documentation/libraries/) which is even better than nested symbols - especially for UX/UI frameworks.

Would be super cool if grommet will support this in the future for their Sketch ressources. Maybe for 2.0?

**Comment by L0ZZI** [comment]
We'll be adding to v2. Coming soon!

**Comment by hxjuneja** [comment]
Hello, have you added the v2 already?
